### ISSUE TITLE
V-WebUI | To-Do List

### ISSUE THREAD

**Issue by malisipi** [webui-dev/v-webui#17]
- [x] `<Window>.is_shown` function is missing d2df9627562a58cfd3b7486b5c9bf916aaa1147f
- [x] `<Window>.set_multi_access` function is missing d2df9627562a58cfd3b7486b5c9bf916aaa1147f
- [x] `<Window>.run` function is missing d2df9627562a58cfd3b7486b5c9bf916aaa1147f
- [x] `<Window>.set_runtime` is missing b6e63e9b2bc3cbc9a5defe14e18696079f670bd8
- [x] Native `<webui.Event>` is not implemented #18 
  - [x] Listening all events `""` is broken (Fix it) 8483f173b125fd24b043c89ae71e5ef8a70b194a
- [x] Support nested usage like javascript (`my_window.bind(/*params*/).bind(/*params*/)`) a118aed041a38a22eee1087bb75fea035b1b6668
- [x] `<Window>.destroy()` is missing 08691cab5836d66d45d92721e9de8ae61f4b5e27
- [x] Use enums instead of const variables (`webui.browser_chrome` -> `.chrome`) 482c4b9d7aa847674d3ae0fc6df3d1741c4a29c5
- [x] Update serve_a_folder example [C Version](https://github.com/alifcommunity/webui/tree/main/examples/C/serve_a_folder) #20 
  - [x] `webui.new_window_id` is missing 4ac9f288bd7821c8a08e93239789363edcd1e04c
  - [x] `webui.get_window_id` is missing (Native implementation required) 4ac9f288bd7821c8a08e93239789363edcd1e04c
- [x] Add real-world V example #19 1c2e30072c046e86c70c8ade06e3253915e57402 d88798ab7f1d08b062f018c69205a0d0a17d5a8d
- [ ] Update V documentation #16 
- [x] `get_new_window_id` is missing https://github.com/alifcommunity/webui/commit/bc5e5b2a56c134656f39f345ef309e6f5a8b9ba2 482c4b9d7aa847674d3ae0fc6df3d1741c4a29c5

**Comment by hassandraga** [comment]
> There're no V way to get element id from event (Create <webui.Event>.element function)

Do you mean `C.webui_event_t.element`?

**Comment by malisipi** [comment]
> Do you mean `C.webui_event_t.element`?

Actually yes and no. C.webui_event_t.element is char and not native type. So the function will get the char, convert it to native string type and return it

**Comment by hassandraga** [comment]
The V wrapper uses a direct call from C-WebUI to V callbacks. It works well, but I made another approach for the [Python](https://github.com/alifcommunity/webui/blob/main/examples/Python/PyPI/Package/src/webui/webui.py), [Go](https://github.com/alifcommunity/webui/blob/main/examples/Go/hello_world/webui/webui.go) and [C++](https://github.com/alifcommunity/webui/blob/main/include/webui.hpp) wrappers. I created an event handler function that receives all events from the WebUI library first, then converts data to the native language format and calls the user callback.

```c
[WebUI] -> [V Wrapper Events Handler] -> [End-user callback]
                 *
                 *
                 * * * Here, you can convert (C.webui_event_t) to (Native V Event struct of your choice)
```

Nothing forced me to use this approach in all three wrappers I made, but I did it anyway just for fun and to learn new things in other languages.

**Comment by malisipi** [comment]
I like the approach. I will implement it as like that. Also it gives the native feeling to developers. While they can use the value directly, why do they need to use a extra function?

**Comment by malisipi** [comment]
`vwebui_event_handler` will handle c-events with `webui_bind`. And `vwebui_event_handler` will trigger v-events. V-events will be registered with `vwebui_bind`. Also `vwebui_bind` will trigger `webui_bind` to register event.

**Comment by malisipi** [comment]
It's nearly done with #18. However it's using global variables that not recommend. I will fix it and merge it

**Comment by malisipi** [comment]
Actually it's still using global variables but `[translated]` flag (in module) is stopping the annoying error.

**Comment by ttytm** [comment]
The last open point might have been resolved with https://github.com/webui-dev/website/pull/3
